workflows:
  ios-ipa:
    name: iOS IPA Build (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 22
      cocoapods: default
      vars:
        BUNDLE_ID: "com.food.manager"
        XCODE_SCHEME: "App"
        SUPABASE_URL: "https://ltuhbuituubmpfcvlppp.supabase.co"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dWhidWl0dXVibXBmY3ZscHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMjc0NTAsImV4cCI6MjA4NzgwMzQ1MH0.6bjGmRIY0bsaOoTZI-qQR9Q9OA1LO-OwSKMB5nSI7zY"
      groups:
        - app_store_credentials
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Install JS dependencies
        script: |
          npm ci
      - name: Prepare iOS project
        script: |
          node scripts/sync_env.mjs
          mkdir -p www
          rm -rf www/*
          cp index.html styles.css app.js api.js config.js manifest.webmanifest sw.js www/
          if [ -d "icons" ]; then
            rm -rf www/icons
            cp -R icons www/icons
          fi
          if [ ! -d "ios/App" ]; then
            npm install --no-save @capacitor/ios@^8.1.0
            npx cap add ios
          fi
          npx cap sync ios
          XCODE_PROJECT_PATH="$(find ios -name '*.xcodeproj' | head -n 1)"
          if [ -z "$XCODE_PROJECT_PATH" ]; then
            echo "Xcode project not found under ios/ after cap sync"
            exit 1
          fi
          IOS_DIR="$(dirname "$XCODE_PROJECT_PATH")"
          WORKSPACE_PATH="$(find "$IOS_DIR" -name '*.xcworkspace' | head -n 1)"
          PODFILE_PATH="$(find "$IOS_DIR" -name Podfile | head -n 1)"
          echo "Using IOS_DIR=$IOS_DIR"
          echo "Using XCODE_PROJECT=$XCODE_PROJECT_PATH"
          if [ -n "$WORKSPACE_PATH" ]; then
            echo "Using XCODE_WORKSPACE=$WORKSPACE_PATH"
          else
            echo "No workspace found, will build with project"
          fi
          if [ -n "$PODFILE_PATH" ]; then
            echo "Found Podfile=$PODFILE_PATH"
          else
            echo "No Podfile found, skipping CocoaPods install"
          fi
          echo "IOS_DIR=$IOS_DIR" >> $CM_ENV
          echo "XCODE_PROJECT=$XCODE_PROJECT_PATH" >> $CM_ENV
          echo "XCODE_WORKSPACE=$WORKSPACE_PATH" >> $CM_ENV
          echo "PODFILE_PATH=$PODFILE_PATH" >> $CM_ENV
      - name: Install CocoaPods
        script: |
          if [ -n "$PODFILE_PATH" ]; then
            cd "$IOS_DIR"
            pod install
          else
            echo "Skipping pod install because Podfile is not present."
          fi
      - name: Set iOS bundle id
        script: |
          INFO_PLIST="$(find "$IOS_DIR" -name Info.plist | grep '/App/' | head -n 1)"
          if [ -z "$INFO_PLIST" ]; then
            INFO_PLIST="$(find "$IOS_DIR" -name Info.plist | head -n 1)"
          fi
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$INFO_PLIST" || true
      - name: Configure code signing
        script: |
          xcode-project use-profiles
      - name: Build signed IPA
        script: |
          if [ -n "$XCODE_WORKSPACE" ]; then
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME"
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME"
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - 1270624963@qq.com
        notify:
          success: true
          failure: true

